### ISSUE TITLE
Invoke-ReimageComputer will not restart target if user is logged in

### ISSUE THREAD

**Issue by n0creativity** [cofl/Cofl.OSDManagement#3]
https://github.com/cofl/Cofl.OSDManagement/blob/b47e05169caf8fc35e5e1bedab8073705fe8a38d/src/Public/Invoke-ReimageComputer.ps1#L87

There should be an option/switch in the command to use the `-Force` option for the `Restart-Computer` command

**Comment by cofl** [comment]
v4.0.8 is now available from https://www.powershellgallery.com/packages/Cofl.OSDManagement/4.0.8
